os: 
  - linux

language: node_js
node_js:
 - 12
 
addons:
 chrome: stable
 
script:
 - npm test

before_install:
- wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo cp chromedriver /usr/bin
